# Generated by Django 5.0.3 on 2024-03-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uname', models.CharField(max_length=100)),
                ('pas', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('api', models.CharField(default='', max_length=36)),
                ('usage', models.IntegerField(default=0)),
            ],
        ),
    ]
